fixup! Fix Crashlytics upload script

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -136,7 +136,13 @@ jobs:
         if: success()
         run: |
           BUILD_DIR=$(xcodebuild -showBuildSettings | grep -m 1 "BUILD_DIR" | cut -d'=' -f2)
-          ${BUILD_DIR%Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run \
+          CRASHLYTICS_PATH="${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
+          if [ ! -f "$CRASHLYTICS_PATH" ]; then
+            echo "Crashlytics upload script not found at: $CRASHLYTICS_PATH"
+            exit 1
+          fi
+
+          "$CRASHLYTICS_PATH" \
           -gsp "NOICommunity/GoogleService-Info.plist" \
           -p ios \
           "$PWD/build/NOICommunity.xcarchive/dSYMs"
